In [10]:
import os
import pandas as pd
pd.set_option('display.max_colwidth', None)

'/home/saxenap/nanoHUB'

In [5]:
df = pd.read_csv(os.environ['APP_DIR'] + '/.cache/Contact.csv', encoding = "ISO-8859-1")
display(df)

/home/saxenap/venv/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3457: DtypeWarning: Columns (4,16,17,18,19,20,24,26,28,32,35,37,47,57,68,84,99,101,104,111,116,117,118,119,121,122,123,125,126,130,131,132,138,147,149,150,151,152,153,170,172,173,174,175,178,180,181,182,183,188,190,191,192,193,194,199,201,202,203) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Id,IsDeleted,MasterRecordId,AccountId,Salutation,FirstName,LastName,MiddleName,OtherStreet,OtherCity,...,NCN_Team__c,hed__Disability_Status__c,hed__Mailing_Address_Inactive__c,hed__SMS_Opt_Out__c,Salutation__c,ML_Webinar_Attendee__c,ML_Webinar_Registrant__c,Recitation_Series_1_Attendee__c,Recitation_Series_1_Registrant__c,X2022_CustSat_Survey_Recipient__c
0,0035w000031Vsp1AAC,0,NaN,0015w0000262NhlAAE,NaN,hubrepo,hubrepo,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0
1,0035w000031Vsp2AAC,0,NaN,0015w0000262NhnAAE,NaN,nanoHUB,support,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
2,0035w000031Vsp3AAC,0,NaN,0015w0000262NhoAAE,NaN,Grid,Statistics,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
3,0035w000031Vsp4AAC,0,NaN,0015w0000262NhpAAE,NaN,NCN,NCN,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
4,0035w000031Vsp5AAC,0,NaN,0015w0000262NhqAAE,NaN,nanoHUB,nanoHUB,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271747,0035w00003btnFCAAY,0,NaN,0015w00002eWVR8AAO,NaN,SAHIL,AMUNDKAR,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
271748,0035w00003btnFDAAY,0,NaN,0015w00002eWVR9AAO,NaN,harrysogar,harrysogar,harrysogar,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
271749,0035w00003btnFEAAY,0,NaN,0015w00002eWVRAAA4,NaN,Hary,Sogar,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
271750,0035w00003btnFFAAY,0,NaN,0015w00002eWVRBAA4,NaN,Nishant,Suryawanshi,Sunil,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0
271751,0035w00003btnFGAAY,0,NaN,0015w00002eWVRCAA4,NaN,Tyler,Dunlap,NaN,NaN,NaN,...,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0

In [30]:
venues_df = df[['Email','nanoHUB_user_ID__c', 'nanoHUB_username__c', 'Lead_Venue__c', 'Venue__c']]
venues_df = venues_df[venues_df['Venue__c'].notnull()]
# venues_df = venues_df.loc[venues_df['Venue__c'] != 'HardBounces11242021']
# venues_df = venues_df.loc[venues_df['Venue__c'] != 'Long-term Users_not recently active']
# venues_df = venues_df.loc[venues_df['Venue__c'] != '2022 Customer Satisfaction Survey recipient;nH_CustSatSurvey2022_import']

filter_strs = [
    'HardBounces11242021', 
    'Long-term Users_not recently active', 
    '2022 Customer Satisfaction Survey',
    'Long-term Users',
    'GibbsUsers12_13_21'
]
# venues_df = venues_df.loc[~venues_df['Venue__c'].str.contains('|'.join(filter_strs))]
venues_df = venues_df.loc[venues_df['Venue__c'] == 'Recitation 1 2021 - R']

display(len(venues_df))
display(venues_df.head())

display(venues_df.tail())

28

,Email,nanoHUB_user_ID__c,nanoHUB_username__c,Lead_Venue__c,Venue__c
2878,jjmiret@ua.es,44853.0,apejj27,NaN,Recitation 1 2021 - R
7179,chang-yong.kim@lightsource.ca,46299.0,cykim66,NaN,Recitation 1 2021 - R
18693,elewuyh@nus.edu.sg,50358.0,yihongwu,NaN,Recitation 1 2021 - R
27970,alexander.knoeller@web.de,53439.0,tentacle,NaN,Recitation 1 2021 - R
33041,alejandro.bautista@correo.buap.mx,79736.0,alexbh,NaN,Recitation 1 2021 - R

,Email,nanoHUB_user_ID__c,nanoHUB_username__c,Lead_Venue__c,Venue__c
194330,ghedirasam@yahoo.fr,225435.0,sami_ghedira,NaN,Recitation 1 2021 - R
195109,montsset90@gmail.com,213776.0,montsset90,NaN,Recitation 1 2021 - R
196403,arobaidi@yahoo.de,226348.0,arobaidi,NaN,Recitation 1 2021 - R
209216,ekapetan@hmu.gr,287980.0,ekapetan,NaN,Recitation 1 2021 - R
227997,chubenko@asu.edu,312674.0,chubenko,NaN,Recitation 1 2021 - R