In [1]:
###
# Objective: obtain researcher ids
# Google Scholar ID_sf: scholar scrape 
# ORCID_sf: ORCID research id search
# Research ID_sf: web of science id search [ORCID can filter] - search as publons
# SCOPUS ID_sf: scopus id search [ORCID can filter]
# reseach gate: either google or own url search 
## Social media scraper
# Facebook via standard google search
# twitter ""
# linkedin ""
# personal websites/webpages: appended to Misc_URLs__c
###

## pull sample of SF contacts

In [2]:
# API settings
api_url = '/services/data/v43.0/sobjects'
external_id = 'Name'
object_id = 'ContactToolAssociation__c'

# login parameters to be handled by Papermill
sql_login_params = {"username": "wang2506_ro", "password": "fnVnwcCS7iT45EsA"}
sf_login_params = {
    "grant_type": "password",
    "client_id": "3MVG95jctIhbyCppj0SNJ75IsZ1y8UPGZtSNF4j8FNVXz.De8Lu4jHm3rjRosAtsHy6qjHx3i4S_QbQzvBePG",
    "client_secret": "D1623C6D3607D4FC8004B92C761DFB6C1F70CCD129C5501E357028DFA00F5764",
    "username":"wang2506@purdue.edu",
    "password":"sf2021shitOPmlIiFMLnrudgC6oSX0WV1T",   
}

In [3]:
import sys
#sys.path.append('/home/users/wang2506/nanohub_salesforce_integ/salesforce')

import pandas as pd
import time
import datetime

from DB2SalesforceAPI import DB2SalesforceAPI

In [4]:
db_1 = DB2SalesforceAPI(sf_login_params)

Obtained Salesforce access token ...... True

In [5]:
query = 'Select ID, firstname, lastname, Email, nanoHUB_user_ID__c, \
    Google_Scholar_ID_sf__c, ORCID_sf__c, Research_ID_sf__c, ResearchGate_ID_sf__c, \
    ResearcherPresence_sf__c, ResearchPresence_Notes_sf__c, \
    Linkedin_Bio__c, Facebook_profile__c, Twitter_profile__c, Misc_URLs__c, \
    Organization_composite__c, Active_duration__c \
    from Contact' #import everyone # limit 10'
c_sample = db_1.query_data(query)

[Success] Bulk job creation successful. Job ID = 7505w00000VpmVTAAZ
{"id":"7505w00000VpmVTAAZ","operation":"query","object":"Contact","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-26T19:07:50.000+0000","systemModstamp":"2021-04-26T19:07:50.000+0000","state":"UploadComplete","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","retries":0,"totalProcessingTime":0}
{"id":"7505w00000VpmVTAAZ","operation":"query","object":"Contact","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-26T19:07:50.000+0000","systemModstamp":"2021-04-26T19:07:50.000+0000","state":"InProgress","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","numberRecordsProcessed":0,"retries":0,"totalProcessingTime":0}
{"id":"7505w00000VpmVTAAZ","operation":"query","object":"Contact","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-26T19:07:50.000+0000","systemModstamp":"2021-04-26T19:07:50.000+0000","state":"InProgress","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","numberRecordsProcessed":0,"retries":0,"totalProcessingTime":0}
{"id":"7505w00000VpmVTAAZ","operation":"query","object":"Contact","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-26T19:07:50.000+0000","systemModstamp":"2021-04-26T19:07:50.000+0000","state":"InProgress","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","numberRecordsProcessed":0,"retries":0,"totalProcessingTime":0}
{"id":"7505w00000VpmVTAAZ","operation":"query","object":"Contact","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-26T19:07:50.000+0000","systemModstamp":"2021-04-26T19:07:50.000+0000","state":"InProgress","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","numberRecordsProcessed":0,"retries":0,"totalProcessingTime":0}
{"id":"7505w00000VpmVTAAZ","operation":"query","object":"Contact","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-26T19:07:50.000+0000","systemModstamp":"2021-04-26T19:08:38.000+0000","state":"JobComplete","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","numberRecordsProcessed":245156,"retries":0,"totalProcessingTime":47114}
[Success] Bulk job completed successfully.

C:\Users\henry\Anaconda3\envs\tf\lib\site-packages\IPython\core\interactiveshell.py:3357: DtypeWarning: Columns (2,4,7,8,11,12,15) have mixed types. Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [6]:
display(c_sample)

,Active_duration__c,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c
0,0.0,nkissebe@gmail.com,NaN,hubrepo,NaN,0035w000031Vsp1AAC,hubrepo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,998.0
1,0.0,support@nanohub.org,NaN,nanoHUB,NaN,0035w000031Vsp2AAC,support,NaN,NaN,NaN,a0r5w00000V42cCAAR,NaN,NaN,NaN,False,NaN,1683.0
2,4105.0,gridstat@nanohub.org,NaN,Grid,NaN,0035w000031Vsp3AAC,Statistics,NaN,NaN,NaN,a0r5w00000V42cCAAR,NaN,NaN,NaN,False,NaN,1684.0
3,0.0,ncn@nanohub.org,NaN,NCN,NaN,0035w000031Vsp4AAC,NCN,NaN,NaN,NaN,a0r5w00000V42cCAAR,NaN,NaN,NaN,False,NaN,1685.0
4,0.0,apps@nanohub.org,NaN,nanoHUB,NaN,0035w000031Vsp5AAC,nanoHUB,NaN,NaN,NaN,a0r5w00000V42cCAAR,NaN,NaN,NaN,False,NaN,1686.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
245151,0.0,NaN,NaN,M,NaN,0035w00003NhXKuAAN,Reddy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,324733.0
245152,0.0,hiruy89@gmail.com,NaN,ENDALKACHEW,NaN,0035w00003NhXKvAAN,MINAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,324734.0
245153,0.0,NaN,NaN,Jasmin,NaN,0035w00003NhXKwAAN,Smith,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,324735.0
245154,0.0,2020ht80525@wilp.bits-pilani.ac.in,NaN,SUDESHNA,NaN,0035w00003NhXKxAAN,V,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,324736.0
245155,0.0,rene.salmingo@chmsc.edu.ph,NaN,Rene,NaN,0035w00003NhXKyAAN,Salmingo,NaN,NaN,NaN,a0r5w00000VRByvAAH,NaN,NaN,NaN,False,NaN,324682.0

In [ ]:
## sort/filter c_sample based on active durations

In [7]:
## filter the contacts st we have valid emails for possible researchers
c_sample2 = c_sample.dropna(subset=['Email','LastName','FirstName'])
c_sample2 = c_sample2.reset_index().drop(columns='index')
display(c_sample2)

,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c
0,malik4002480@cloud.neduet.edu.pk,NaN,YAMNA,NaN,0035w00003KtFpgAAF,MALIK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314189.0
1,disha0107@gmail.com,NaN,Disha,NaN,0035w00003KtFphAAF,Bisto,NaN,NaN,NaN,a0r5w00000V43QoAAJ,NaN,NaN,NaN,False,NaN,314191.0
2,shafiqpapa20027@gmail.com,NaN,NIMRA,NaN,0035w00003KtFpiAAF,SHAFIQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314196.0
3,lr_gannavarapu@ece.iitr.ac.in,NaN,LAKSHMI,NaN,0035w00003MZe7TAAT,GANNAVARAPU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317881.0
4,pranaleerane@gmail.com,NaN,Pranali,NaN,0035w00003MZe7XAAT,Rane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317887.0
5,voramegh18@gmail.com,NaN,Megh,NaN,0035w00003MZe7UAAT,Vora,NaN,NaN,NaN,a0r5w00000V42kEAAR,NaN,NaN,NaN,False,NaN,317884.0
6,yashsakpal0504@gmail.com,NaN,Yash,NaN,0035w00003MZe7VAAT,Sakpal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317885.0

In [8]:
## determine email domains
email_domains = c_sample2['Email'].to_list()

for i,j in enumerate(email_domains):
    j_temp = j.split('@')
    email_domains[i] = j_temp[-1]

print(email_domains[:3])

['cloud.neduet.edu.pk', 'gmail.com', 'gmail.com']

## organization pointer fill

In [9]:
##
# 1. pull SF organization codes 
# 2. replace pointers in c_sample (i.e., Organization_composite__c col) with the corresponding org name
##

In [10]:
orgs_query = 'Select ID, Name, Domain__c from organization__c'
orgs_all = db_1.query_data(orgs_query)
display(orgs_all.head(5))

[Success] Bulk job creation successful. Job ID = 7505w00000VK8vxAAD
{"id":"7505w00000VK8vxAAD","operation":"query","object":"organization__c","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-14T16:20:47.000+0000","systemModstamp":"2021-04-14T16:20:47.000+0000","state":"UploadComplete","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","retries":0,"totalProcessingTime":0}
{"id":"7505w00000VK8vxAAD","operation":"query","object":"organization__c","createdById":"0055w00000DM5bOAAT","createdDate":"2021-04-14T16:20:47.000+0000","systemModstamp":"2021-04-14T16:20:51.000+0000","state":"JobComplete","concurrencyMode":"Parallel","contentType":"CSV","apiVersion":47.0,"jobType":"V2Query","lineEnding":"LF","columnDelimiter":"COMMA","numberRecordsProcessed":6404,"retries":0,"totalProcessingTime":791}
[Success] Bulk job completed successfully.

,Domain__c,Id,Name
0,upenn.edu,a0r5w00000V42c0AAB,university of pennsylvania
1,fer.hr,a0r5w00000V42c1AAB,fer
2,wheatoncollege.edu,a0r5w00000V42c2AAB,wheaton college (ma)
3,case.edu,a0r5w00000V42c3AAB,case western reserve university
4,iitgn.ac.in,a0r5w00000V42c4AAB,"indian institute of technology, gandhinagar"

In [11]:
orgs_all = orgs_all.rename(columns={'Id':'Organization_composite__c'})

In [12]:
display(orgs_all.head(5))

,Domain__c,Organization_composite__c,Name
0,upenn.edu,a0r5w00000V42c0AAB,university of pennsylvania
1,fer.hr,a0r5w00000V42c1AAB,fer
2,wheatoncollege.edu,a0r5w00000V42c2AAB,wheaton college (ma)
3,case.edu,a0r5w00000V42c3AAB,case western reserve university
4,iitgn.ac.in,a0r5w00000V42c4AAB,"indian institute of technology, gandhinagar"

In [13]:
# left inner join
c_sample2 = c_sample2.merge(orgs_all,how='left',on='Organization_composite__c',suffixes=[None,'Delete'])
display(c_sample2.head(5))

,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c,Domain__c,Name
0,malik4002480@cloud.neduet.edu.pk,NaN,YAMNA,NaN,0035w00003KtFpgAAF,MALIK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314189.0,NaN,NaN
1,disha0107@gmail.com,NaN,Disha,NaN,0035w00003KtFphAAF,Bisto,NaN,NaN,NaN,a0r5w00000V43QoAAJ,NaN,NaN,NaN,False,NaN,314191.0,unb.ca,university of new brunswick
2,shafiqpapa20027@gmail.com,NaN,NIMRA,NaN,0035w00003KtFpiAAF,SHAFIQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314196.0,NaN,NaN
3,lr_gannavarapu@ece.iitr.ac.in,NaN,LAKSHMI,NaN,0035w00003MZe7TAAT,GANNAVARAPU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317881.0,NaN,NaN
4,pranaleerane@gmail.com,NaN,Pranali,NaN,0035w00003MZe7XAAT,Rane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317887.0,NaN,NaN

In [14]:
c_sample2 = c_sample2.rename(columns={'Name':'org_name'})
display(c_sample2.head(5))

,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c,Domain__c,org_name
0,malik4002480@cloud.neduet.edu.pk,NaN,YAMNA,NaN,0035w00003KtFpgAAF,MALIK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314189.0,NaN,NaN
1,disha0107@gmail.com,NaN,Disha,NaN,0035w00003KtFphAAF,Bisto,NaN,NaN,NaN,a0r5w00000V43QoAAJ,NaN,NaN,NaN,False,NaN,314191.0,unb.ca,university of new brunswick
2,shafiqpapa20027@gmail.com,NaN,NIMRA,NaN,0035w00003KtFpiAAF,SHAFIQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314196.0,NaN,NaN
3,lr_gannavarapu@ece.iitr.ac.in,NaN,LAKSHMI,NaN,0035w00003MZe7TAAT,GANNAVARAPU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317881.0,NaN,NaN
4,pranaleerane@gmail.com,NaN,Pranali,NaN,0035w00003MZe7XAAT,Rane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317887.0,NaN,NaN

In [15]:
# extract org names for later comparisons
org_names = c_sample2['org_name'].to_list()

## string search utils

In [16]:
## Levenshtein distance handler
from Levenshtein import distance as levenshtein_distance

## Google_Scholar_ID_sf__c search

In [17]:
## details: https://scholarly.readthedocs.io/en/latest/quickstart.html
# preamble: proxy bypass google scholar bot wall via free-proxy [if fails, link to internal tor w/in brave docs]
# 1. extract and combine firstname and lastname in a list
# 2. search via scholarly - store generators
# 3. filter results for firstname/lastname + email combination
#    - email/domain + firstname/lastname > email > firstname + lastname comb
# 4. if exists, build google scholar url
# 5. populate dataframe with the results
##

In [18]:
from scholarly import scholarly, ProxyGenerator
from fp.fp import FreeProxy
import time

In [19]:
pg = ProxyGenerator()
pg.FreeProxies()
scholarly.use_proxy(pg)

In [20]:
def names_calc(in_df,dump_mid=False,exact=False):
    fullnames = []
    for i in range(in_df.shape[0]):
        temp_fn = ' '.join([in_df.iloc[i,2],in_df.iloc[i,5]])
        
        # dump middle name - issues with exact searches
        if dump_mid == True:
            temp_fn_list = temp_fn.split(' ') # otherwise if fn = n1 n2, then wont get list form
            if len(temp_fn_list) >= 3:
                fullnames.append(' '.join([temp_fn_list[0],temp_fn_list[-1]]))
            else:
                fullnames.append(' '.join(temp_fn_list))
        else:
            fullnames.append(temp_fn)
        
        # convert fullnames into exact strings
        if exact == True:
            fullnames[-1] = '"' + fullnames[-1] + '"'
        
    return fullnames

In [21]:
# fullnames list
fullnames = names_calc(c_sample2)

In [22]:
print(fullnames[:3])

['YAMNA MALIK', 'Disha Bisto', 'NIMRA SHAFIQ']

In [23]:
gs_ids = [] #google scholar IDs

In [24]:
import numpy as np

In [25]:
# search iteratively and store
for ind,val in enumerate(fullnames):
    author_gen = scholarly.search_author(val)
    list_auth_gen = list(author_gen)
    
    time.sleep(np.random.randint(1,3)) # rng seconds of sleep
    if len(list_auth_gen) != 0:
        # iteratively perform name based levenshtein capping
        for test_case in list_auth_gen:
            if levenshtein_distance(test_case['name'],val) <= 5: #less than or equal to 5 edits
                if test_case['email_domain'] == email_domains[ind]:
                    # .edu domains
                    if email_domains[ind][-3:] == 'edu':
                        gs_url = 'https://scholar.google.com/citations?user={}&hl=en&oi=ao'.format(test_case['scholar_id'])
                        gs_ids.append(gs_url)
                        break
                    else: #hack
                        gs_url = 'https://scholar.google.com/citations?user={}&hl=en&oi=ao'.format(test_case['scholar_id'])
                        gs_ids.append(gs_url)
                        break
                elif test_case['affiliation'] == org_names[ind]:
                    gs_url = 'https://scholar.google.com/citations?user={}&hl=en&oi=ao'.format(test_case['scholar_id'])
                    gs_ids.append(gs_url)
                    break
    else:
        gs_ids.append('')

In [26]:
gs_ids

['', '', '', '', '', '', '']

In [27]:
c_sample2['Google_Scholar_ID_sf__c'] = gs_ids
display(c_sample2.head(5))

,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c,Domain__c,org_name
0,malik4002480@cloud.neduet.edu.pk,NaN,YAMNA,,0035w00003KtFpgAAF,MALIK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314189.0,NaN,NaN
1,disha0107@gmail.com,NaN,Disha,,0035w00003KtFphAAF,Bisto,NaN,NaN,NaN,a0r5w00000V43QoAAJ,NaN,NaN,NaN,False,NaN,314191.0,unb.ca,university of new brunswick
2,shafiqpapa20027@gmail.com,NaN,NIMRA,,0035w00003KtFpiAAF,SHAFIQ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,314196.0,NaN,NaN
3,lr_gannavarapu@ece.iitr.ac.in,NaN,LAKSHMI,,0035w00003MZe7TAAT,GANNAVARAPU,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317881.0,NaN,NaN
4,pranaleerane@gmail.com,NaN,Pranali,,0035w00003MZe7XAAT,Rane,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,317887.0,NaN,NaN

## ORCID search

In [29]:
## details: rely on the fullnames list created earlier
# 1. design ORCID search URLs to find candidate ORCIDs
# 2. iteratively search through possible ORCID urls
# 3. levensthein distance calculation for organization [not done - adds variance to gs results]
# 4. [far future] if need more thoroughness can use https://orcid.github.io/orcid-api-tutorial/; although this is overkill
##

In [30]:
# didn't really work
from urllib.request import urlopen
from bs4 import BeautifulSoup

In [31]:
# not as powerful, but works
from googlesearch import search
import re

In [70]:
ORCID_urls = []

In [71]:
# populate ORCID urls
for i in fullnames:
    temp_name = i.split(' ')
    test = search('{} {} ORCID'.format(temp_name[0],temp_name[-1]),tld='com', lang='en', \
                  num=5, start=0, stop=5, pause=np.random.randint(2,5))
    list_test = [j for j in test]
    if len(list_test) == 0:
        ORCID_urls.append('')
    else:   
        for ind,j in enumerate(list_test):
            orcid_matches = re.findall(r'orcid.org/\d+-\d+-\d+-\d+',j)
            if len(orcid_matches) > 0:
                # take the first match and move on
                temp_url = 'https://{}'.format(orcid_matches[0])
                ORCID_urls.append(temp_url)
                break

            if ind == len(list_test)-1:
                ORCID_urls.append('')
                break

In [77]:
c_sample2['ORCID_sf__c'] = ORCID_urls
display(c_sample2.head(5))

,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c,Domain__c,org_name
0,malik4002480@cloud.neduet.edu.pk,NaN,YAMNA,,0035w00003KtFpgAAF,MALIK,NaN,NaN,,NaN,NaN,NaN,NaN,False,NaN,314189.0,NaN,NaN
1,disha0107@gmail.com,NaN,Disha,,0035w00003KtFphAAF,Bisto,NaN,NaN,,a0r5w00000V43QoAAJ,NaN,NaN,NaN,False,NaN,314191.0,unb.ca,university of new brunswick
2,shafiqpapa20027@gmail.com,NaN,NIMRA,,0035w00003KtFpiAAF,SHAFIQ,NaN,NaN,,NaN,NaN,NaN,NaN,False,NaN,314196.0,NaN,NaN
3,lr_gannavarapu@ece.iitr.ac.in,NaN,LAKSHMI,,0035w00003MZe7TAAT,GANNAVARAPU,NaN,NaN,,NaN,NaN,NaN,NaN,False,NaN,317881.0,NaN,NaN
4,pranaleerane@gmail.com,NaN,Pranali,,0035w00003MZe7XAAT,Rane,NaN,NaN,,NaN,NaN,NaN,NaN,False,NaN,317887.0,NaN,NaN

## Research ID_sf

In [ ]:
## Do the same thing as ORCID ID search
# rather than web of science researcherID - use publons as the filter

In [91]:
wos_researchers = [] #web of science researcherIDs

In [92]:
# populate researcherIDs
for i in fullnames:
    temp_name = i.split(' ')
    test = search('{} {} publons'.format(temp_name[0],temp_name[-1]),tld='com', lang='en', \
                  num=5, start=0, stop=5, pause=np.random.randint(2,5))
    list_test = [j for j in test]
    if len(list_test) == 0:
        wos_researchers.append('')
    else:
        for ind,j in enumerate(list_test):
            wos_matches = re.findall(r'publons.com/researcher/\d+',j)
            if len(wos_matches) > 0:
                # take the first match and move on
                temp_url = 'https://{}/{}-{}'.format(wos_matches[0],temp_name[0],temp_name[-1])
                wos_researchers.append(temp_url)
                break

            if ind == len(list_test)-1:
                wos_researchers.append('')
                break

In [93]:
c_sample2['Research_ID_sf__c'] = wos_researchers
display(c_sample2.head(5))

,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c,Domain__c,org_name
0,malik4002480@cloud.neduet.edu.pk,NaN,YAMNA,,0035w00003KtFpgAAF,MALIK,NaN,NaN,,NaN,NaN,NaN,,False,NaN,314189.0,NaN,NaN
1,disha0107@gmail.com,NaN,Disha,,0035w00003KtFphAAF,Bisto,NaN,NaN,,a0r5w00000V43QoAAJ,NaN,NaN,,False,NaN,314191.0,unb.ca,university of new brunswick
2,shafiqpapa20027@gmail.com,NaN,NIMRA,,0035w00003KtFpiAAF,SHAFIQ,NaN,NaN,,NaN,NaN,NaN,,False,NaN,314196.0,NaN,NaN
3,lr_gannavarapu@ece.iitr.ac.in,NaN,LAKSHMI,,0035w00003MZe7TAAT,GANNAVARAPU,NaN,NaN,,NaN,NaN,NaN,,False,NaN,317881.0,NaN,NaN
4,pranaleerane@gmail.com,NaN,Pranali,,0035w00003MZe7XAAT,Rane,NaN,NaN,,NaN,NaN,NaN,,False,NaN,317887.0,NaN,NaN

## SCOPUS

In [ ]:
## scopus results don't show up via google search - will need their own API
# see https://dev.elsevier.com/ when you have time

## reseach gate

In [ ]:
## Follow procedure from ORCID + publons

In [109]:
research_gate_ids = [] #web of science researcherIDs

In [110]:
# populate research gates
for i in fullnames:
    temp_name = i.split(' ')
    test = search('{} {} research gate'.format(temp_name[0],temp_name[-1]),tld='com', lang='en', \
                  num=5, start=0, stop=5, pause=np.random.randint(2,5))
    list_test = [j for j in test]
    if len(list_test) == 0:
        research_gate_ids.append('')
    else:
        for ind,j in enumerate(list_test):
            rg_matches = re.findall(r'researchgate.net/profile/\w+-\w+',j)
            if len(rg_matches) > 0:
                # take the first match and move on
                temp_url = 'https://{}'.format(rg_matches[0])
                research_gate_ids.append(temp_url)
                break

            if ind == len(list_test)-1:
                research_gate_ids.append('')
                break

In [112]:
c_sample2['ResearchGate_ID_sf__c'] = research_gate_ids
display(c_sample2.head(5))

,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c,Domain__c,org_name
0,malik4002480@cloud.neduet.edu.pk,NaN,YAMNA,,0035w00003KtFpgAAF,MALIK,NaN,NaN,,NaN,https://researchgate.net/profile/Amna-Malik,NaN,,False,NaN,314189.0,NaN,NaN
1,disha0107@gmail.com,NaN,Disha,,0035w00003KtFphAAF,Bisto,NaN,NaN,,a0r5w00000V43QoAAJ,,NaN,,False,NaN,314191.0,unb.ca,university of new brunswick
2,shafiqpapa20027@gmail.com,NaN,NIMRA,,0035w00003KtFpiAAF,SHAFIQ,NaN,NaN,,NaN,https://researchgate.net/profile/Nimra-Hasnain,NaN,,False,NaN,314196.0,NaN,NaN
3,lr_gannavarapu@ece.iitr.ac.in,NaN,LAKSHMI,,0035w00003MZe7TAAT,GANNAVARAPU,NaN,NaN,,NaN,,NaN,,False,NaN,317881.0,NaN,NaN
4,pranaleerane@gmail.com,NaN,Pranali,,0035w00003MZe7XAAT,Rane,NaN,NaN,,NaN,https://researchgate.net/profile/Pranali-Rane,NaN,,False,NaN,317887.0,NaN,NaN

In [111]:
research_gate_ids # the sans-levenshtein dist method pulls in more people - albeit some of them are clearly wrong

['https://researchgate.net/profile/Amna-Malik',
 '',
 'https://researchgate.net/profile/Nimra-Hasnain',
 '',
 'https://researchgate.net/profile/Pranali-Rane',
 'https://researchgate.net/profile/Megh-Vora',
 '']

In [108]:
fullnames

['YAMNA MALIK',
 'Disha Bisto',
 'NIMRA SHAFIQ',
 'LAKSHMI GANNAVARAPU',
 'Pranali Rane',
 'Megh Vora',
 'Yash Sakpal']