In [5]:
%run main_file.py

Obtained Salesforce access token ...... True
logging dir exists, you're good

2021-08-15 21:34:19,085| WARNING | /home/nanoHUB-user/venv/lib/python3.8/site-packages/IPython/utils/py3compat.py:168: DtypeWarning: Columns (3,5,10,12,13,14,16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(compiler(f.read(), fname, 'exec'), glob, loc)

2021-08-15 21:34:19,085 - [WARNING] py.warnings [warnings._showwarnmsg:109]: /home/nanoHUB-user/venv/lib/python3.8/site-packages/IPython/utils/py3compat.py:168: DtypeWarning: Columns (3,5,10,12,13,14,16) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(compiler(f.read(), fname, 'exec'), glob, loc)

,Active_duration__c,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c
0,7477.0,olschner@cremat.com,NaN,Fred,NaN,0035w000034JHBGAA4,Olschner,NaN,NaN,NaN,NaN,https://researchgate.net/profile/Frederick-Ols...,NaN,NaN,False,NaN,4586.0
1,7168.0,terje.finstad@fys.uio.no,NaN,Terje,https://scholar.google.com/citations?user=R1pX...,0035w000034JFkyAAG,Finstad,NaN,NaN,https://orcid.org/0000-0001-9219-6722,NaN,https://researchgate.net/profile/Terje-Finstad,GK 3/25/21,NaN,True,NaN,3267.0

,Active_duration__c,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c
247677,NaN,asdf1234@invalidaddress5.org,NaN,Bounce,NaN,0035w00003DA2NpAAL,Test2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN
247678,NaN,lisagundy@arizona.edu,NaN,Lisa,NaN,0035w00003EE0MoAAL,Gundy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,NaN

,Active_duration__c,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c
0,7477.0,olschner@cremat.com,NaN,Fred,NaN,0035w000034JHBGAA4,Olschner,NaN,NaN,NaN,NaN,https://researchgate.net/profile/Frederick-Ols...,NaN,NaN,False,NaN,4586.0
1,7168.0,terje.finstad@fys.uio.no,NaN,Terje,https://scholar.google.com/citations?user=R1pX...,0035w000034JFkyAAG,Finstad,NaN,NaN,https://orcid.org/0000-0001-9219-6722,NaN,https://researchgate.net/profile/Terje-Finstad,GK 3/25/21,NaN,True,NaN,3267.0

,Active_duration__c,Email,Facebook_profile__c,FirstName,Google_Scholar_ID_sf__c,Id,LastName,Linkedin_Bio__c,Misc_URLs__c,ORCID_sf__c,Organization_composite__c,ResearchGate_ID_sf__c,ResearchPresence_Notes_sf__c,Research_ID_sf__c,ResearcherPresence_sf__c,Twitter_profile__c,nanoHUB_user_ID__c
228192,0.0,emoehring19@gmail.com,NaN,Elle,NaN,0035w00003FVlpKAAT,M,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False,NaN,303818.0
228193,0.0,uwaiszaki104@gmail.com,NaN,uwais,NaN,0035w00003PZv7VAAT,zaki,NaN,NaN,NaN,a0r5w00000V43O1AAJ,NaN,NaN,NaN,False,NaN,327976.0

['cremat.com', 'fys.uio.no', 'purdue.edu']

KeyboardInterrupt: