In [1]:
## build researcher events, student events, and self-study events
## researcher are simply those with NH citations

In [2]:
import sys

import pandas as pd
import numpy as np
import time
import datetime
import os
from nanoHUB.application import Application
from nanoHUB.configuration import ClusteringConfiguration
from nanoHUB.pipeline.geddes.data import get_default_s3_client
from nanoHUB.dataaccess.lake import S3FileMapper

from nanoHUB.clustering.infra import get_mike_only_clustered_users, get_xufeng_only_clustered_users, get_mike_xufeng_clustered_users
from nanoHUB.clustering.infra import create_clusters_repository, add_cluster_info, get_all_clustered_users, get_all_self_study_users, get_all_self_identified_users

nanoHUB - Serving Students, Researchers & Instructors

In [3]:
pd.set_option('display.max_columns', None)
cwd = os.getcwd()

In [4]:
## determine starting year
#if cache_flag == False:
start_year_base = 1999 #2000
#start_year_base = 2019 #2000


#else:
#     print('check the saved file')
#    start_year_base = int(user_breakdown_df['year_month'].to_list()[-1][:4])

In [5]:
application = Application.get_instance()
nanohub_db = application.new_db_engine('nanohub')
nanohub_metrics_db = application.new_db_engine('nanohub_metrics')
wang159_myrmekes_db = application.new_db_engine('rfm_data')

s3_client = get_default_s3_client(application)
derived_data_file_path = 'derived_data_for_users.csv'
processed_mapper = S3FileMapper(s3_client, ClusteringConfiguration().bucket_name_processed)

In [6]:
def Annualized_Usage(nanohub_metrics_db,start_year,list_usernames,list_title):
    today = datetime.datetime.today()
    print(today)    
    #cache_r_track = pd.DataFrame()
    #cache_si_track = pd.DataFrame()
    #cache_si_track['user'] = self_identified_track
    active_track = []
    active_date = []
    
    ## computer has memory limits, so split toolstart into branches
    # this filters and finds the research usage in nanohub
    while start_year < today.year+1:
        start_year += 1
        end_date = r"'"+str(start_year)+r"-01-01'"
        start_date = r"'"+str(start_year-2)+r"-01-01'"

        print('end date: '+ str(end_date))
        for i in range(1,13):
            if i < 10:
                start_date = r"'"+str(start_year-1)+r"-0"+str(i)+r"-01'"
                end_date = r"'"+str(start_year)+r"-0"+str(i)+r"-01'"
            else:
                start_date = r"'"+str(start_year-1)+r"-"+str(i)+r"-01'"
                end_date = r"'"+str(start_year)+r"-"+str(i)+r"-01'"

            sql_query = "select user from toolstart where user in " + str(tuple(list_usernames))\
                +" and datetime <= "+end_date+" and datetime >= "+start_date
            active_users = pd.read_sql_query(sql_query, nanohub_metrics_db)
            #print('date '+str(end_date)+' '+list_title+' partial',active_users.drop_duplicates()[0:10])
            print('date '+str(end_date)+' '+list_title+' length',len(active_users.drop_duplicates()))

            #count the number of active users and append into an array
            active_track.append(active_users.drop_duplicates().shape[0])
            active_date.append(end_date)


        print('end date: '+ str(end_date))
        #display(researcher_track)
        #display(researcher_track)

        cache_track = pd.DataFrame()
        cache_track['track'] = active_track
        cache_track.to_csv(cwd+'/cached_data/'+list_title+'_track.csv')
        cache_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_'+list_title+'_track.csv')
        cache_track = []
        
        cache_datetrack = pd.DataFrame()
        cache_datetrack['date'] = active_date
        cache_datetrack['track'] = active_track
        cache_datetrack.to_csv(cwd+'/cached_data/'+list_title+'_date_track.csv')
        cache_datetrack.to_csv(cwd+'/cached_data/'+ str(start_year)+'_'+list_title+'_date_track.csv')
        cache_datetrack = []
        

    return active_track

## Cumulative classroom/research/self-study

In [7]:
clustered_df = get_all_clustered_users(processed_mapper, derived_data_file_path)
clustered_df['nanoHUB_user_ID__c'] = clustered_df['id']
clustered_NH_ids = clustered_df['nanoHUB_user_ID__c']
display(len(clustered_NH_ids))

78167

In [8]:
mike_clustered_users_df = get_mike_only_clustered_users(processed_mapper, derived_data_file_path)
mike_clustered_users_df['nanoHUB_user_ID__c'] = mike_clustered_users_df['id']
mike_clustered_NH_ids = mike_clustered_users_df['nanoHUB_user_ID__c']
display(len(mike_clustered_users_df))

[WARNING] [warnings - py.warnings]: /home/gekco/nanoHUB/nanoHUB/clustering/infra.py:334: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  return df[df[column_name].str.contains(search_for)]
 [warnings._showwarnmsg:109]

16825

In [9]:
xufeng_clustered_users_df = get_xufeng_only_clustered_users(processed_mapper, derived_data_file_path)
xufeng_clustered_users_df['nanoHUB_user_ID__c'] = xufeng_clustered_users_df['id']
xufeng_clustered_NH_ids = xufeng_clustered_users_df['nanoHUB_user_ID__c']
display(len(xufeng_clustered_users_df))

14997

In [10]:
mike_xufeng_clustered_users_df = get_mike_xufeng_clustered_users(processed_mapper, derived_data_file_path)
mike_xufeng_clustered_users_df['nanoHUB_user_ID__c'] = mike_xufeng_clustered_users_df['id']
mike_xufeng_clustered_NH_ids = mike_xufeng_clustered_users_df['nanoHUB_user_ID__c']
display(len(mike_xufeng_clustered_users_df))

46345

In [11]:
# raise

In [12]:
self_study_df = get_all_self_study_users(processed_mapper, derived_data_file_path)
self_study_df['nanoHUB_user_ID__c'] = self_study_df['id']
self_study_NH_ids = self_study_df['nanoHUB_user_ID__c']
self_study_usernames = self_study_df['username'].tolist()

print('self_study_NH_ids length = ',len(self_study_NH_ids))
print('self_study_usernames length = ',len(self_study_usernames))
print('self_study_usernames samples = ',self_study_usernames[0:10])

self_study_NH_ids length =  194524
self_study_usernames length =  194524
self_study_usernames samples =  ['hubrepo', 'admin', 'support', 'gridstat', 'ncn', 'nanohub', 'repo', 'violin', 'mireles', 'k_dadesh']

In [13]:
self_identified_df = get_all_self_identified_users(processed_mapper, derived_data_file_path)
self_identified_df['nanoHUB_user_ID__c'] = self_identified_df['id']
self_identified_NH_ids = self_identified_df['nanoHUB_user_ID__c']
self_identified_usernames = self_identified_df['username'].tolist()
print('length of self_identified_NH_ids',len(self_identified_NH_ids))
display(self_identified_df.head())
#print(self_identified_usernames)

length of self_identified_NH_ids 4037

,id,name,username,email,registerDate,lastvisitDate,first_citation_at,number_citations,profile_key,has_researcher_profile,number_simulations,uid,clusters,mike_fall_2008,xufeng_fall_2008,mike_spring_2008,xufeng_spring_2008,mike_fall_2009,xufeng_fall_2009,mike_spring_2009,xufeng_spring_2009,mike_fall_2010,xufeng_fall_2010,mike_spring_2010,xufeng_spring_2010,mike_fall_2011,xufeng_fall_2011,mike_spring_2011,xufeng_spring_2011,mike_fall_2012,xufeng_fall_2012,mike_spring_2012,xufeng_spring_2012,mike_fall_2013,xufeng_fall_2013,mike_spring_2013,xufeng_spring_2013,mike_fall_2014,xufeng_fall_2014,mike_spring_2014,xufeng_spring_2014,mike_fall_2015,xufeng_fall_2015,mike_spring_2015,xufeng_spring_2015,mike_fall_2016,xufeng_fall_2016,mike_spring_2016,xufeng_spring_2016,mike_fall_2017,xufeng_fall_2017,mike_spring_2017,xufeng_spring_2017,mike_fall_2018,xufeng_fall_2018,mike_spring_2018,xufeng_spring_2018,mike_fall_2019,xufeng_fall_2019,mike_spring_2019,xufeng_spring_2019,mike_fall_2020,xufeng_fall_2020,mike_spring_2020,xufeng_spring_2020,mike_fall_2021,xufeng_fall_2021,nanoHUB_user_ID__c
895,2579,Stefan Birner,birner,stefan.birner@nextnano.com,2006-05-05 07:36:09,2020-01-13 15:58:33,NaN,0.0,[orcid],True,52.0,2579.0,['mike_spring_2010'],False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,2579
1176,2862,Mark Lundstrom,lundstro,lundstro@purdue.edu,2004-12-06 22:01:25,2022-02-08 16:28:36,NaN,0.0,"[googlescholar, researchgateid]",True,2345.0,2862.0,"['xufeng_fall_2008', 'xufeng_spring_2008', 'xu...",False,True,False,True,False,False,False,False,False,True,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,2862
1473,3159,Tamara J. Moore,tmoore,tmoore@purdue.edu,2003-09-03 21:18:50,2021-10-07 19:58:59,NaN,0.0,[orcid],True,38.0,3159.0,['xufeng_fall_2020'],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,3159
1796,3482,Gerhard Klimeck,gekco,gekco@purdue.edu,2004-04-10 17:58:53,2022-02-10 14:45:37,NaN,0.0,"[orcid, googlescholar, researcherid, researchg...",True,18677.0,3482.0,"['xufeng_fall_2009', 'xufeng_spring_2009', 'xu...",False,False,False,False,False,True,False,True,False,True,False,True,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,3482
1897,3583,Eric Pop,epop,epop@stanford.edu,2006-02-09 20:57:14,2021-09-04 07:19:40,NaN,0.0,"[orcid, googlescholar]",True,90.0,3583.0,['xufeng_fall_2012'],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,3583

In [14]:
allusers_df = processed_mapper.read(derived_data_file_path)
display(allusers_df.head(5))
#display(allusers_usernames)
display(allusers_df.loc[allusers_df['username'].isnull()])
#display(allusers_df.loc[allusers_df['username'].notna()])

allusers_df = allusers_df.loc[allusers_df['username'].notna()]
display(allusers_df.loc[allusers_df['username'].isnull()])

allusers_usernames = allusers_df['username'].tolist()

[WARNING] [warnings - py.warnings]: /tmp/ipykernel_6145/3153650497.py:1: DtypeWarning: Columns (6) have mixed types.Specify dtype option on import or set low_memory=False.
  allusers_df = processed_mapper.read(derived_data_file_path)
 [warnings._showwarnmsg:109]

,id,name,username,email,registerDate,lastvisitDate,first_citation_at,number_citations,profile_key,has_researcher_profile,number_simulations,uid,clusters,mike_fall_2008,xufeng_fall_2008,mike_spring_2008,xufeng_spring_2008,mike_fall_2009,xufeng_fall_2009,mike_spring_2009,xufeng_spring_2009,mike_fall_2010,xufeng_fall_2010,mike_spring_2010,xufeng_spring_2010,mike_fall_2011,xufeng_fall_2011,mike_spring_2011,xufeng_spring_2011,mike_fall_2012,xufeng_fall_2012,mike_spring_2012,xufeng_spring_2012,mike_fall_2013,xufeng_fall_2013,mike_spring_2013,xufeng_spring_2013,mike_fall_2014,xufeng_fall_2014,mike_spring_2014,xufeng_spring_2014,mike_fall_2015,xufeng_fall_2015,mike_spring_2015,xufeng_spring_2015,mike_fall_2016,xufeng_fall_2016,mike_spring_2016,xufeng_spring_2016,mike_fall_2017,xufeng_fall_2017,mike_spring_2017,xufeng_spring_2017,mike_fall_2018,xufeng_fall_2018,mike_spring_2018,xufeng_spring_2018,mike_fall_2019,xufeng_fall_2019,mike_spring_2019,xufeng_spring_2019,mike_fall_2020,xufeng_fall_2020,mike_spring_2020,xufeng_spring_2020,mike_fall_2021,xufeng_fall_2021
0,998,hubrepo hubrepo,hubrepo,nkissebe@gmail.com,2014-11-13 21:09:09,NaN,NaN,0.0,[],False,0.0,NaN,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,1000,CMS Admin Manager,admin,support@nanohub.org,NaN,NaN,NaN,0.0,[],False,0.0,NaN,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,1683,nanoHUB support,support,support@nanohub.org,2008-11-19 22:51:04,2008-11-19 23:55:30,NaN,0.0,[],False,2.0,1683.0,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,1684,Grid Statistics,gridstat,gridstat@nanohub.org,2008-11-18 17:29:56,2020-02-14 18:50:14,NaN,0.0,[],False,0.0,NaN,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,1685,NCN NCN,ncn,ncn@nanohub.org,2008-11-11 19:17:04,NaN,NaN,0.0,[],False,0.0,NaN,[],False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

,id,name,username,email,registerDate,lastvisitDate,first_citation_at,number_citations,profile_key,has_researcher_profile,number_simulations,uid,clusters,mike_fall_2008,xufeng_fall_2008,mike_spring_2008,xufeng_spring_2008,mike_fall_2009,xufeng_fall_2009,mike_spring_2009,xufeng_spring_2009,mike_fall_2010,xufeng_fall_2010,mike_spring_2010,xufeng_spring_2010,mike_fall_2011,xufeng_fall_2011,mike_spring_2011,xufeng_spring_2011,mike_fall_2012,xufeng_fall_2012,mike_spring_2012,xufeng_spring_2012,mike_fall_2013,xufeng_fall_2013,mike_spring_2013,xufeng_spring_2013,mike_fall_2014,xufeng_fall_2014,mike_spring_2014,xufeng_spring_2014,mike_fall_2015,xufeng_fall_2015,mike_spring_2015,xufeng_spring_2015,mike_fall_2016,xufeng_fall_2016,mike_spring_2016,xufeng_spring_2016,mike_fall_2017,xufeng_fall_2017,mike_spring_2017,xufeng_spring_2017,mike_fall_2018,xufeng_fall_2018,mike_spring_2018,xufeng_spring_2018,mike_fall_2019,xufeng_fall_2019,mike_spring_2019,xufeng_spring_2019,mike_fall_2020,xufeng_fall_2020,mike_spring_2020,xufeng_spring_2020,mike_fall_2021,xufeng_fall_2021
77305,82487,Geraldine Young,NaN,f948941@rmqkr.net,2013-05-22 20:04:55,2013-06-14 20:51:07,NaN,0.0,[],False,39.0,82487.0,"['mike_fall_2008', 'xufeng_fall_2008', 'mike_s...",True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True
211599,281303,Nataly Cárdenas,NaN,njcardenasvasquez@gmail.com,2020-03-20 17:26:07,2020-03-20 17:26:07,NaN,0.0,[],False,4.0,281303.0,"['mike_fall_2008', 'xufeng_fall_2008', 'mike_s...",True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True,True

Empty DataFrame
Columns: [id, name, username, email, registerDate, lastvisitDate, first_citation_at, number_citations, profile_key, has_researcher_profile, number_simulations, uid, clusters, mike_fall_2008, xufeng_fall_2008, mike_spring_2008, xufeng_spring_2008, mike_fall_2009, xufeng_fall_2009, mike_spring_2009, xufeng_spring_2009, mike_fall_2010, xufeng_fall_2010, mike_spring_2010, xufeng_spring_2010, mike_fall_2011, xufeng_fall_2011, mike_spring_2011, xufeng_spring_2011, mike_fall_2012, xufeng_fall_2012, mike_spring_2012, xufeng_spring_2012, mike_fall_2013, xufeng_fall_2013, mike_spring_2013, xufeng_spring_2013, mike_fall_2014, xufeng_fall_2014, mike_spring_2014, xufeng_spring_2014, mike_fall_2015, xufeng_fall_2015, mike_spring_2015, xufeng_spring_2015, mike_fall_2016, xufeng_fall_2016, mike_spring_2016, xufeng_spring_2016, mike_fall_2017, xufeng_fall_2017, mike_spring_2017, xufeng_spring_2017, mike_fall_2018, xufeng_fall_2018, mike_spring_2018, xufeng_spring_2018, mike_fall_2019, xufeng_fall_2019, mike_spring_2019, xufeng_spring_2019, mike_fall_2020, xufeng_fall_2020, mike_spring_2020, xufeng_spring_2020, mike_fall_2021, xufeng_fall_2021]
Index: []

In [15]:
#sql_query_simtotal = "select distinct user from toolstart;"
#simtotal_users = pd.read_sql_query(sql_query_simtotal, nanohub_metrics_db) #engine_metrics #.drop_duplicates()

In [16]:
#print('simtotal_users length', len(simtotal_users))
#display(simtotal_users)

In [17]:
print('clustered users',clustered_NH_ids.shape)
print('selfstudy users',self_study_NH_ids.shape)
print('self_study_usernames',len(self_study_usernames))
print('self identified researchers',self_identified_NH_ids.shape)
print('all users',allusers_df.shape)

clustered users (78167,)
selfstudy users (194524,)
self_study_usernames 194524
self identified researchers (4037,)
all users (272689, 67)

In [18]:
frames = [clustered_df, self_study_df]
contacts_df = pd.concat(frames)

In [19]:
## need to filter self-study-nh-ids with the researchers

In [20]:
## This researcher determination is based entirely on the results of research authors on nanohub
## i.e., we use the researcher information on db2

In [21]:
sql_query = 'select id, uid, author from jos_citations'
jos_citations = pd.read_sql_query(sql_query, nanohub_db)
display(jos_citations.head(2))
print(jos_citations.shape)

         id   uid                                             author
0  10000001  5568  Weber, Bent; Mahapatra, Suddhasatta; Ryu, Hoon...
1  10000002  5568  Andrawis, Robert; Bermeo, Jose; Charles, James...

(4203, 3)

In [22]:
t1_authors = jos_citations['author'].to_list()
t1_authors2 = [] #[j.split(';') for i,j in enumerate(t1_authors)]

In [23]:
for i,j in enumerate(t1_authors):
    try:
        holder = j.split(';')
        if len(holder) > 1: 
            for k,l in enumerate(holder):
                if l[0] == ' ':
                    holder[k] = l[1:]
        t1_authors2.append(holder)
    except:
        garb = True

In [24]:
t1_authors32 = [item for sublist in t1_authors2 for item in sublist]
t1_authors3 = set(t1_authors32)
print(len(t1_authors3))

6860

In [25]:
## extract all researchers with nh ids
rw_ids = []
need_search = []
for i,j in enumerate(t1_authors3):
    if '{{' in j:
        rw_ids.append(i)
    else:
        need_search.append(i)

In [26]:
## from the rw_ids, extract the nanohub userids
# can obtain usernames from the DB2 table
rw_ids2 = np.array(list(t1_authors3))[rw_ids]
for i,j in enumerate(rw_ids2):
    begin = j.index('{{')
    rw_ids2[i] = j[begin+2:-2]
print(len(rw_ids2))

2079

In [27]:
# need to obtain usernames
sql_query = "select id,name,username from jos_users where id in "+str(tuple(rw_ids2))
rw_researchers = pd.read_sql_query(sql_query,nanohub_db)
display(rw_researchers.head(2))

     id                name username
0  1742   H.-S. Philip Wong  hspwong
1  1767  Osama Munir Nayfeh  onayfeh

In [28]:
## need to obtain the username/ids from those people without nh ids explicitly spec'd in jos_citations
ns2 = np.array(list(t1_authors3))[need_search]
ns2 = ns2[1:]

In [29]:
tuple(ns2)[:5]

('Md Al-Rashid',
 'Alok Charurvedi',
 'Bruce Boecker',
 'Mohammad Rajabzadeh',
 'Patricia Carey')

In [30]:
sql_query = "select id,name,username from jos_users where name in "+str(tuple(ns2))
ns2_researchers = pd.read_sql_query(sql_query,nanohub_db)
display(ns2_researchers.head(2))

       id              name     username
0  282167  Aarthi Narayanan  aarthin0102
1  280280       Abani Patra     apatra01

In [31]:
## combine the usernames into one data structure
researcher_usernames = rw_researchers['username'].to_list() + ns2_researchers['username'].to_list()
print('list of researchers who have cited nanohub  researcher_usernames=',len(researcher_usernames))

list of researchers who have cited nanohub  researcher_usernames= 3046

In [32]:
#bool_search3 = np.in1d(np.array(researcher_usernames),np.array(self_identified_usernames))
#researcher_usernames = np.where(~bool_search3)[0].tolist()
#display(len(researcher_usernames))

#display(len(self_identified_usernames))

print('self_identified_usernames can have overlap with researchers',len(self_identified_usernames))
#exclude the self-identified researchers from the users who have done research on nanohub
#display(self_identified_usernames)
#display(researcher_usernames)
print('self_identified_usernames patial list', self_identified_usernames[0:10])
print('researcher_usernames partial list',researcher_usernames[0:10])

#bool_search3 = np.in1d(np.array(self_identified_usernames),np.array(researcher_usernames))
#print('bool_search3 length of ',len(bool_search3))
#print('bool_search3 partial list',bool_search3)

#self_identified_usernames_index = np.where(~bool_search3)[0].tolist()
si_usernames = self_identified_usernames
r_usernames = researcher_usernames


print(len(si_usernames))
si_usernames = [x for x in si_usernames if x not in r_usernames]
print(len(si_usernames))
print(si_usernames[:10])

self_identified_usernames can have overlap with researchers 4037
self_identified_usernames patial list ['birner', 'lundstro', 'tmoore', 'gekco', 'epop', 'alexwei', 'xfong', 'fgarcia', 'kalna', '3ksnn64']
researcher_usernames partial list ['hspwong', 'onayfeh', 'accelrys', 'himadri', 'fossum', 'garose', 'reimers', 'liping', 'bwu', 'fortes']
4037
3942
['tmoore', 'alexwei', '3ksnn64', 'aeislam', 'simbawz', 'aeberurs', 'kaze', 'tuocvungoc', 'ismail', 'ortizc']

In [33]:
self_identified_usernames = si_usernames


#print('self_identified_usernames_index partial list',self_identified_usernames_index[0:10])
#print('self_identified_usernames_index length',len(self_identified_usernames_index))


#display(self_identified_df)
#display(self_identified_df['username'][self_identified_usernames_index])


print('researcher_usernames',len(researcher_usernames))

print('self_identified_usernames reduced by overlap with researchers',len(self_identified_usernames))
print('self_identified_usernames some samples',self_identified_usernames[0:10])

researcher_usernames 3046
self_identified_usernames reduced by overlap with researchers 3942
self_identified_usernames some samples ['tmoore', 'alexwei', '3ksnn64', 'aeislam', 'simbawz', 'aeberurs', 'kaze', 'tuocvungoc', 'ismail', 'ortizc']

In [34]:
#need to take out the researchers and citing authors from the list of selfstudy users. 
#
print('number of self-study users self_study_usernames',len(self_study_usernames))
print('take out len(researcher_usernames)',len(researcher_usernames))
print('take out len(self_identified_usernames)',len(self_identified_usernames))

self_study_usernames = [x for x in self_study_usernames if x not in researcher_usernames]
print('number of self-study users self_study_usernames',len(self_study_usernames))
self_study_usernames = [x for x in self_study_usernames if x not in self_identified_usernames]
print('number of self-study users self_study_usernames',len(self_study_usernames))

number of self-study users self_study_usernames 194524
take out len(researcher_usernames) 3046
take out len(self_identified_usernames) 3942
number of self-study users self_study_usernames 192480
number of self-study users self_study_usernames 189161

In [35]:
# researcher_ids = rw_researchers['id'].to_list() + ns2_researchers['id'].to_list()
# print('researchers/citation',len(researcher_ids))



# bool_search2 = np.in1d(np.array(self_study_NH_ids.tolist()),np.array(researcher_ids))


# # Note, researchers can possibly be doubled counted within clusters!!
# # sf_researchers = np.where(bool_search2)[0].tolist() 
# sf_self_study = np.where(~bool_search2)[0].tolist()
# print('self-study users',len(sf_self_study))

# bool_search2_2 = np.in1d(np.array(sf_self_study),np.array(self_identified_NH_ids.tolist()))
# sf_self_study = np.where(~bool_search2_2)[0].tolist()

# print('sf_self_study',len(sf_self_study))
# print('self_study_NH_ids',len(self_study_NH_ids.to_list()))
# print('self_identified_NH_ids',len(self_identified_NH_ids.to_list()))


# # self study user usernames
# ts_query = 'select id,username from jos_users where id in ' + str(tuple(self_study_NH_ids.dropna().to_list())) 
# #sf_contact_ids['nanoHUB_user_ID__c']))
# ss_NH_username = pd.read_sql_query(ts_query,nanohub_db)
# ss_NH_username_usernames = ss_NH_username['username'].tolist()

In [36]:
#restart analysis here 
#restart analysis here 
#restart analysis here 
#restart analysis here

In [37]:
today = datetime.datetime.today()
print(today)

2022-02-22 15:50:59.550039

In [38]:
## caching check 
try:
    user_breakdown_df = pd.read_csv(cwd+'/cached_data/nh_user_breakdown.csv')
    print(user_breakdown_df)
    cache_flag = True
except:
    cache_flag = False

In [39]:
#print(user_breakdown_df['year_month'].to_list()[-1][:4])

In [40]:
from copy import deepcopy

In [41]:
all_months_list = list()
for this_year in range(start_year_base+1,today.year+2):
    if cache_flag == True:
        for this_month in range(1,today.month+1):
            all_months_list.append(datetime.datetime(this_year, this_month, 1))
    else:
        for this_month in range(1,12+1):
            all_months_list.append(datetime.datetime(this_year, this_month, 1))

cache_all_month_list = pd.DataFrame()
cache_all_month_list['Date'] = all_months_list
cache_all_month_list.to_csv(cwd+'/cached_data/all_months_list.csv')
cache_all_month_list.to_csv(cwd+'/cached_data/'+ str(start_year_base)+'_all_months_list.csv')
cache_all_month_list = []
print('allmonths partial list',all_months_list[0:36])

allmonths partial list [datetime.datetime(2000, 1, 1, 0, 0), datetime.datetime(2000, 2, 1, 0, 0), datetime.datetime(2000, 3, 1, 0, 0), datetime.datetime(2000, 4, 1, 0, 0), datetime.datetime(2000, 5, 1, 0, 0), datetime.datetime(2000, 6, 1, 0, 0), datetime.datetime(2000, 7, 1, 0, 0), datetime.datetime(2000, 8, 1, 0, 0), datetime.datetime(2000, 9, 1, 0, 0), datetime.datetime(2000, 10, 1, 0, 0), datetime.datetime(2000, 11, 1, 0, 0), datetime.datetime(2000, 12, 1, 0, 0), datetime.datetime(2001, 1, 1, 0, 0), datetime.datetime(2001, 2, 1, 0, 0), datetime.datetime(2001, 3, 1, 0, 0), datetime.datetime(2001, 4, 1, 0, 0), datetime.datetime(2001, 5, 1, 0, 0), datetime.datetime(2001, 6, 1, 0, 0), datetime.datetime(2001, 7, 1, 0, 0), datetime.datetime(2001, 8, 1, 0, 0), datetime.datetime(2001, 9, 1, 0, 0), datetime.datetime(2001, 10, 1, 0, 0), datetime.datetime(2001, 11, 1, 0, 0), datetime.datetime(2001, 12, 1, 0, 0), datetime.datetime(2002, 1, 1, 0, 0), datetime.datetime(2002, 2, 1, 0, 0), datetime.datetime(2002, 3, 1, 0, 0), datetime.datetime(2002, 4, 1, 0, 0), datetime.datetime(2002, 5, 1, 0, 0), datetime.datetime(2002, 6, 1, 0, 0), datetime.datetime(2002, 7, 1, 0, 0), datetime.datetime(2002, 8, 1, 0, 0), datetime.datetime(2002, 9, 1, 0, 0), datetime.datetime(2002, 10, 1, 0, 0), datetime.datetime(2002, 11, 1, 0, 0), datetime.datetime(2002, 12, 1, 0, 0)]

In [42]:
#print(self_identified_usernames[0:50])
#print('str(tuple(self_identified_usernames))',str(tuple(self_identified_usernames)))
#print(self_study_usernames[0:50])
#print(allusers_usernames[0:50])

In [43]:
skip_first_section=1
if (skip_first_section==0):
    #cache_r_track = pd.DataFrame()
    #cache_si_track = pd.DataFrame()
    #cache_si_track['user'] = self_identified_track
    self_identified_track = []
    researcher_track = []
    self2_track = []
    simtotal_track = []

    ## computer has memory limits, so split toolstart into branches
    # this filters and finds the research usage in nanohub
    start_year = deepcopy(start_year_base)
    while start_year < today.year+1:
        start_year += 1
        print('start year: '+ str(start_year))
        end_date = r"'"+str(start_year)+r"-01-01'"
        start_date = r"'"+str(start_year-2)+r"-01-01'"

        for i in range(1,13):
            if i < 10:
                start_date = r"'"+str(start_year-1)+r"-0"+str(i)+r"-01'"
                end_date = r"'"+str(start_year)+r"-0"+str(i)+r"-01'"
            else:
                start_date = r"'"+str(start_year-1)+r"-"+str(i)+r"-01'"
                end_date = r"'"+str(start_year)+r"-"+str(i)+r"-01'"

            sql_query_researcher = "select user from toolstart where user in " + str(tuple(researcher_usernames))\
                +" and datetime <= "+end_date+" and datetime >= "+start_date
            researcher_users = pd.read_sql_query(sql_query_researcher, nanohub_metrics_db)
            print('date'+str(start_date)+ 'research_users partial',researcher_users.drop_duplicates()[0:10])
            print('date'+str(start_date)+ 'research_users =',len(researcher_users.drop_duplicates()))

            #researcher_track contains the number of users in this specific month 
            researcher_track.append(researcher_users.drop_duplicates().shape[0])

            sql_query_self_identified = "select user from toolstart where user in " + str(tuple(self_identified_usernames))\
                +" and datetime <= "+end_date+" and datetime >= "+start_date
            self_identified_users = pd.read_sql_query(sql_query_self_identified, nanohub_metrics_db)
            #print('date'+str(start_date)+ 'self_identified_users partial',self_identified_users.drop_duplicates()[0:10])
            #print('date'+str(start_date)+ 'self_identified_users =',len(self_identified_users.drop_duplicates()))

            #self_identified_track contains the number of users in this specific month 
            self_identified_track.append(self_identified_users.drop_duplicates().shape[0])
            #print('start date',start_date)
            #display(researcher_track)


            sql_query_self = "select user from toolstart where user in " + str(tuple(self_study_usernames))\
                +" and user != 'instanton' and user != 'gridstat' and datetime <= "+end_date+" and datetime >= "+start_date
            self2_users = pd.read_sql_query(sql_query_self, nanohub_metrics_db) #engine_metrics #.drop_duplicates()
            #print('date'+str(start_date)+ 'self2_users partial',self2_users.drop_duplicates()[0:10])
            #print('date'+str(start_date)+ 'self2_users =',len(self2_users.drop_duplicates()))
            self2_track.append(self2_users.drop_duplicates().shape[0])        

            # query for any job start activity and therefore not examin all registered users.
            sql_query_simtotal = "select user from toolstart where datetime <= "+end_date+" and datetime >= "+start_date
            simtotal_users = pd.read_sql_query(sql_query_simtotal, nanohub_metrics_db) #engine_metrics #.drop_duplicates()
            #print('date'+str(start_date)+ 'simtotal_users partial',simtotal_users.drop_duplicates()[0:10])
            #print('date'+str(start_date)+ 'simtotal_users =',len(simtotal_users.drop_duplicates()))
            simtotal_track.append(simtotal_users.drop_duplicates().shape[0])        

            print('date'+str(start_date)+ 'total =',len(simtotal_users.drop_duplicates()), \
                 'self2_users =',len(self2_users.drop_duplicates()), \
                 'researcher_users =',len(researcher_users.drop_duplicates()), \
                 'self_identified_users =',len(self_identified_users.drop_duplicates())     )
            #print('simtotal_track=',simtotal_track)
            #print('self2_track =',self2_track)
            #print('researcher_track',researcher_track)


        print('start year: '+ str(start_year))
        #display(researcher_track)
        #display(researcher_track)

        cache_r_track = pd.DataFrame()
        cache_r_track['track'] = researcher_track
        cache_r_track.to_csv(cwd+'/cached_data/researcher_track.csv')
        cache_r_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_researcher_track.csv')
        cache_r_track = []

        cache_si_track = pd.DataFrame()
        cache_si_track['track'] = self_identified_track
        cache_si_track.to_csv(cwd+'/cached_data/self_identified_track.csv')
        cache_si_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_self_identified_track.csv')
        cache_si_track = []

        cache_s2_track = pd.DataFrame()
        cache_s2_track['track'] = self2_track
        cache_s2_track.to_csv(cwd+'/cached_data/self2_track.csv')
        cache_s2_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_self2_track.csv')
        cache_s2_track = []

        cache_simtotal_track = pd.DataFrame()
        cache_simtotal_track['track'] = simtotal_track
        cache_simtotal_track.to_csv(cwd+'/cached_data/simtotal_track.csv')
        cache_simtotal_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_simtotal_track.csv')
        cache_simtotal_track = []

In [44]:
## filter the self study folks against those of researchers
# need to pull the researcher sf ids

In [45]:
#sf_contact_ids = contacts_df['nanoHUB_user_ID__c'][sf_self_study]

In [46]:
# sf_contact_ids = sf_contact_ids.reset_index()
# sf_contact_ids = sf_contact_ids.drop(columns='index')
# display(sf_contact_ids)

In [47]:
# tuple(sf_contact_ids['nanoHUB_user_ID__c'])[:5]

In [48]:
# tuple(self_study_NH_ids.dropna().to_list())[:5]

In [49]:
## loading in toolstart

In [50]:
# clustered user usernames
tc_query = 'select id,username from jos_users where id in ' +str(tuple(clustered_NH_ids))
clustered_NH_username = pd.read_sql_query(tc_query,nanohub_db)
display(len(clustered_NH_username))

tc_query = 'select id,username from jos_users where id in ' +str(tuple(mike_clustered_NH_ids))
mike_clustered_NH_username = pd.read_sql_query(tc_query,nanohub_db)
display(len(mike_clustered_NH_username))

tc_query = 'select id,username from jos_users where id in ' +str(tuple(xufeng_clustered_NH_ids))
xufeng_clustered_NH_username = pd.read_sql_query(tc_query,nanohub_db)
display(len(xufeng_clustered_NH_username))

tc_query = 'select id,username from jos_users where id in ' +str(tuple(mike_xufeng_clustered_NH_ids))
mike_xufeng_clustered_NH_username = pd.read_sql_query(tc_query,nanohub_db)
display(len(mike_xufeng_clustered_NH_username))

78167

16825

14997

46345

In [51]:
## self study user usernames
#ts_query = 'select id,username from jos_users where id in ' + str(tuple(self_study_NH_ids.dropna().to_list())) 
##sf_contact_ids['nanoHUB_user_ID__c']))
#ss_NH_username = pd.read_sql_query(ts_query,nanohub_db)

In [52]:
## cache the researchers, self-study, and clustered users
cache_r_nhid = pd.DataFrame()
#cache_r_nhid['nhid'] = researcher_ids
cache_r_nhid['username'] = researcher_usernames

cache_si_nhid = pd.DataFrame()
#cache_si_nhid['nhid'] = self_identified_NH_ids.to_list()
cache_si_nhid['username'] = self_identified_usernames

cache_ss_nhid = pd.DataFrame()
#cache_ss_nhid['nhid'] = ss_NH_username['id']
cache_ss_nhid['username'] = self_study_usernames

cache_c_nhid = pd.DataFrame()
cache_c_nhid['nhid'] = clustered_NH_username['id']
cache_c_nhid['username'] = clustered_NH_username['username']

cache_cm_nhid = pd.DataFrame()
cache_cm_nhid['nhid'] = mike_clustered_NH_username['id']
cache_cm_nhid['username'] = mike_clustered_NH_username['username']

cache_cx_nhid = pd.DataFrame()
cache_cx_nhid['nhid'] = xufeng_clustered_NH_username['id']
cache_cx_nhid['username'] = xufeng_clustered_NH_username['username']

cache_cmx_nhid = pd.DataFrame()
cache_cmx_nhid['nhid'] = mike_xufeng_clustered_NH_username['id']
cache_cmx_nhid['username'] = mike_xufeng_clustered_NH_username['username']

In [53]:
print(cache_r_nhid.head(2))
print(cache_si_nhid.head(2))
print(cache_ss_nhid.head(2))
print(cache_c_nhid.head(2))
print(cache_cm_nhid.head(2))
print(cache_cx_nhid.head(2))
print(cache_cmx_nhid.head(2))

  username
0  hspwong
1  onayfeh
  username
0   tmoore
1  alexwei
  username
0  hubrepo
1    admin
     nhid    username
0  166284  0.yao.yuan
1  344801  007sribabu
   nhid username
0  1767  onayfeh
1  1909  reimers
   nhid username
0  1848   kevdog
1  1852  himadri
   nhid      username
0  1794        mar889
1  2136  ashtone_rose

In [54]:
cache_r_nhid.to_csv(cwd+'/cached_data/researcher_ids.csv')
cache_si_nhid.to_csv(cwd+'/cached_data/self_identified_ids.csv')
cache_ss_nhid.to_csv(cwd+'/cached_data/ss_ids.csv')
cache_c_nhid.to_csv(cwd+'/cached_data/class_ids.csv')
cache_cm_nhid.to_csv(cwd+'/cached_data/class_m_ids.csv')
cache_cx_nhid.to_csv(cwd+'/cached_data/class_x_ids.csv')
cache_cmx_nhid.to_csv(cwd+'/cached_data/class_mx_ids.csv')

In [55]:
# clustered_NH_username2;researcher_NH_username2;self_NH_username2
clustered_track = []
clustered_m_track = []
clustered_x_track = []
clustered_mx_track = []
self_track = []

# clustered_track_per = []
# self_track_per = []
# researcher_track_per = []

In [56]:
#ss_NH_username.shape #old

In [57]:
#call the annual number analysis as a function
start_year = start_year_base
#clustered_track       = Annualized_Usage(nanohub_metrics_db,start_year,clustered_NH_username['username'],'clustered_all')
#clustered_m_track     = Annualized_Usage(nanohub_metrics_db,start_year,mike_clustered_NH_username['username'],'clustered_m')
#clustered_x_track     = Annualized_Usage(nanohub_metrics_db,start_year,xufeng_clustered_NH_username['username'],'clustered_x')
#clustered_mx_track    = Annualized_Usage(nanohub_metrics_db,start_year,mike_xufeng_clustered_NH_username['username'],'clustered_mx')
#researcher_track      = Annualized_Usage(nanohub_metrics_db,start_year,researcher_usernames,'citingauthor')
#self_identified_track = Annualized_Usage(nanohub_metrics_db,start_year,self_identified_usernames,'selfidentifiedauthors')
#self_study_track      = Annualized_Usage(nanohub_metrics_db,start_year,self_study_usernames,'unclassified')
simtotal_track        = Annualized_Usage(nanohub_metrics_db,start_year,allusers_usernames,'simtotal')

2022-02-22 15:51:05.423437
end date: '2000-01-01'
date '2000-01-01' simtotal length 0
date '2000-02-01' simtotal length 0
date '2000-03-01' simtotal length 58
date '2000-04-01' simtotal length 72
date '2000-05-01' simtotal length 88
date '2000-06-01' simtotal length 96
date '2000-07-01' simtotal length 101
date '2000-08-01' simtotal length 119
date '2000-09-01' simtotal length 215
date '2000-10-01' simtotal length 269
date '2000-11-01' simtotal length 327
date '2000-12-01' simtotal length 378
end date: '2000-12-01'
end date: '2001-01-01'
date '2001-01-01' simtotal length 409
date '2001-02-01' simtotal length 616
date '2001-03-01' simtotal length 753
date '2001-04-01' simtotal length 779
date '2001-05-01' simtotal length 804
date '2001-06-01' simtotal length 811
date '2001-07-01' simtotal length 817
date '2001-08-01' simtotal length 806
date '2001-09-01' simtotal length 807
date '2001-10-01' simtotal length 814
date '2001-11-01' simtotal length 775
date '2001-12-01' simtotal length 742
end date: '2001-12-01'
end date: '2002-01-01'
date '2002-01-01' simtotal length 684
date '2002-02-01' simtotal length 665
date '2002-03-01' simtotal length 662
date '2002-04-01' simtotal length 647
date '2002-05-01' simtotal length 394
date '2002-06-01' simtotal length 388
date '2002-07-01' simtotal length 394
date '2002-08-01' simtotal length 404
date '2002-09-01' simtotal length 445
date '2002-10-01' simtotal length 485
date '2002-11-01' simtotal length 503
date '2002-12-01' simtotal length 480
end date: '2002-12-01'
end date: '2003-01-01'
date '2003-01-01' simtotal length 457
date '2003-02-01' simtotal length 478
date '2003-03-01' simtotal length 834
date '2003-04-01' simtotal length 853
date '2003-05-01' simtotal length 825
date '2003-06-01' simtotal length 847
date '2003-07-01' simtotal length 856
date '2003-08-01' simtotal length 860
date '2003-09-01' simtotal length 973
date '2003-10-01' simtotal length 1012
date '2003-11-01' simtotal length 1020
date '2003-12-01' simtotal length 1032
end date: '2003-12-01'
end date: '2004-01-01'
date '2004-01-01' simtotal length 982
date '2004-02-01' simtotal length 987
date '2004-03-01' simtotal length 1009
date '2004-04-01' simtotal length 1071
date '2004-05-01' simtotal length 1054
date '2004-06-01' simtotal length 818
date '2004-07-01' simtotal length 857
date '2004-08-01' simtotal length 857
date '2004-09-01' simtotal length 997
date '2004-10-01' simtotal length 1038
date '2004-11-01' simtotal length 1086
date '2004-12-01' simtotal length 1083
end date: '2004-12-01'
end date: '2005-01-01'
date '2005-01-01' simtotal length 1007
date '2005-02-01' simtotal length 1090
date '2005-03-01' simtotal length 1154
date '2005-04-01' simtotal length 1103
date '2005-05-01' simtotal length 1068
date '2005-06-01' simtotal length 1080
date '2005-07-01' simtotal length 1104
date '2005-08-01' simtotal length 1191
date '2005-09-01' simtotal length 1300
date '2005-10-01' simtotal length 1386
date '2005-11-01' simtotal length 1551
date '2005-12-01' simtotal length 1674
end date: '2005-12-01'
end date: '2006-01-01'
date '2006-01-01' simtotal length 1670
date '2006-02-01' simtotal length 1898
date '2006-03-01' simtotal length 2153
date '2006-04-01' simtotal length 2393
date '2006-05-01' simtotal length 2534
date '2006-06-01' simtotal length 2698
date '2006-07-01' simtotal length 2959
date '2006-08-01' simtotal length 3062
date '2006-09-01' simtotal length 3397
date '2006-10-01' simtotal length 3573
date '2006-11-01' simtotal length 4073
date '2006-12-01' simtotal length 4293
end date: '2006-12-01'
end date: '2007-01-01'
date '2007-01-01' simtotal length 4357
date '2007-02-01' simtotal length 4907
date '2007-03-01' simtotal length 5263
date '2007-04-01' simtotal length 5484
date '2007-05-01' simtotal length 5568
date '2007-06-01' simtotal length 5707
date '2007-07-01' simtotal length 5693
date '2007-08-01' simtotal length 5791
date '2007-09-01' simtotal length 5848
date '2007-10-01' simtotal length 6027
date '2007-11-01' simtotal length 6030
date '2007-12-01' simtotal length 5956
end date: '2007-12-01'
end date: '2008-01-01'
date '2008-01-01' simtotal length 5953
date '2008-02-01' simtotal length 6317
date '2008-03-01' simtotal length 6378
date '2008-04-01' simtotal length 6339
date '2008-05-01' simtotal length 6328
date '2008-06-01' simtotal length 6301
date '2008-07-01' simtotal length 6336
date '2008-08-01' simtotal length 6395
date '2008-09-01' simtotal length 6410
date '2008-10-01' simtotal length 6542
date '2008-11-01' simtotal length 6897
date '2008-12-01' simtotal length 6808
end date: '2008-12-01'
end date: '2009-01-01'
date '2009-01-01' simtotal length 6872
date '2009-02-01' simtotal length 7289
date '2009-03-01' simtotal length 7065
date '2009-04-01' simtotal length 7207
date '2009-05-01' simtotal length 7055
date '2009-06-01' simtotal length 6947
date '2009-07-01' simtotal length 6912
date '2009-08-01' simtotal length 6828
date '2009-09-01' simtotal length 6950
date '2009-10-01' simtotal length 7342
date '2009-11-01' simtotal length 7528
date '2009-12-01' simtotal length 7406
end date: '2009-12-01'
end date: '2010-01-01'
date '2010-01-01' simtotal length 7414
date '2010-02-01' simtotal length 7991
date '2010-03-01' simtotal length 8346
date '2010-04-01' simtotal length 8226
date '2010-05-01' simtotal length 8151
date '2010-06-01' simtotal length 8376
date '2010-07-01' simtotal length 8516
date '2010-08-01' simtotal length 8657
date '2010-09-01' simtotal length 8879
date '2010-10-01' simtotal length 9388
date '2010-11-01' simtotal length 9890
date '2010-12-01' simtotal length 9913
end date: '2010-12-01'
end date: '2011-01-01'
date '2011-01-01' simtotal length 9802
date '2011-02-01' simtotal length 10017
date '2011-03-01' simtotal length 10704
date '2011-04-01' simtotal length 10531
date '2011-05-01' simtotal length 10522
date '2011-06-01' simtotal length 10464
date '2011-07-01' simtotal length 10502
date '2011-08-01' simtotal length 10494
date '2011-09-01' simtotal length 10684
date '2011-10-01' simtotal length 10965
date '2011-11-01' simtotal length 11330
date '2011-12-01' simtotal length 11137
end date: '2011-12-01'
end date: '2012-01-01'
date '2012-01-01' simtotal length 10877
date '2012-02-01' simtotal length 11634
date '2012-03-01' simtotal length 11986
date '2012-04-01' simtotal length 11959
date '2012-05-01' simtotal length 11785
date '2012-06-01' simtotal length 11760
date '2012-07-01' simtotal length 11793
date '2012-08-01' simtotal length 11955
date '2012-09-01' simtotal length 12077
date '2012-10-01' simtotal length 12529
date '2012-11-01' simtotal length 12499
date '2012-12-01' simtotal length 12390
end date: '2012-12-01'
end date: '2013-01-01'
date '2013-01-01' simtotal length 12111
date '2013-02-01' simtotal length 12355
date '2013-03-01' simtotal length 12775
date '2013-04-01' simtotal length 12752
date '2013-05-01' simtotal length 12522
date '2013-06-01' simtotal length 12424
date '2013-07-01' simtotal length 12420
date '2013-08-01' simtotal length 12389
date '2013-09-01' simtotal length 12687
date '2013-10-01' simtotal length 13380
date '2013-11-01' simtotal length 13483
date '2013-12-01' simtotal length 13511
end date: '2013-12-01'
end date: '2014-01-01'
date '2014-01-01' simtotal length 13080
date '2014-02-01' simtotal length 13367
date '2014-03-01' simtotal length 13470
date '2014-04-01' simtotal length 13447
date '2014-05-01' simtotal length 13091
date '2014-06-01' simtotal length 12802
date '2014-07-01' simtotal length 12636
date '2014-08-01' simtotal length 12352
date '2014-09-01' simtotal length 12269
date '2014-10-01' simtotal length 12521
date '2014-11-01' simtotal length 12578
date '2014-12-01' simtotal length 12241
end date: '2014-12-01'
end date: '2015-01-01'
date '2015-01-01' simtotal length 12049
date '2015-02-01' simtotal length 12422
date '2015-03-01' simtotal length 12308
date '2015-04-01' simtotal length 12565
date '2015-05-01' simtotal length 12180
date '2015-06-01' simtotal length 11969
date '2015-07-01' simtotal length 11914
date '2015-08-01' simtotal length 12089
date '2015-09-01' simtotal length 12406
date '2015-10-01' simtotal length 13165
date '2015-11-01' simtotal length 13445
date '2015-12-01' simtotal length 13264
end date: '2015-12-01'
end date: '2016-01-01'
date '2016-01-01' simtotal length 13026
date '2016-02-01' simtotal length 13088
date '2016-03-01' simtotal length 13085
date '2016-04-01' simtotal length 13198
date '2016-05-01' simtotal length 13225
date '2016-06-01' simtotal length 13248
date '2016-07-01' simtotal length 13491
date '2016-08-01' simtotal length 13730
date '2016-09-01' simtotal length 14238
date '2016-10-01' simtotal length 14944
date '2016-11-01' simtotal length 15149
date '2016-12-01' simtotal length 15572
end date: '2016-12-01'
end date: '2017-01-01'
date '2017-01-01' simtotal length 15318
date '2017-02-01' simtotal length 15593
date '2017-03-01' simtotal length 15986
date '2017-04-01' simtotal length 16131
date '2017-05-01' simtotal length 15823
date '2017-06-01' simtotal length 15842
date '2017-07-01' simtotal length 15879
date '2017-08-01' simtotal length 15946
date '2017-09-01' simtotal length 16502
date '2017-10-01' simtotal length 16875
date '2017-11-01' simtotal length 16911
date '2017-12-01' simtotal length 16617
end date: '2017-12-01'
end date: '2018-01-01'
date '2018-01-01' simtotal length 16178
date '2018-02-01' simtotal length 16424
date '2018-03-01' simtotal length 16362
date '2018-04-01' simtotal length 16108
date '2018-05-01' simtotal length 16116
date '2018-06-01' simtotal length 16025
date '2018-07-01' simtotal length 15911
date '2018-08-01' simtotal length 16319
date '2018-09-01' simtotal length 16618
date '2018-10-01' simtotal length 16753
date '2018-11-01' simtotal length 17288
date '2018-12-01' simtotal length 17011
end date: '2018-12-01'
end date: '2019-01-01'
date '2019-01-01' simtotal length 16690
date '2019-02-01' simtotal length 16945
date '2019-03-01' simtotal length 17128
date '2019-04-01' simtotal length 17403
date '2019-05-01' simtotal length 17377
date '2019-06-01' simtotal length 17348
date '2019-07-01' simtotal length 17328
date '2019-08-01' simtotal length 17099
date '2019-09-01' simtotal length 17089
date '2019-10-01' simtotal length 17268
date '2019-11-01' simtotal length 17439
date '2019-12-01' simtotal length 17243
end date: '2019-12-01'
end date: '2020-01-01'
date '2020-01-01' simtotal length 16579
date '2020-02-01' simtotal length 16843
date '2020-03-01' simtotal length 16841
date '2020-04-01' simtotal length 17251
date '2020-05-01' simtotal length 17830
date '2020-06-01' simtotal length 18108
date '2020-07-01' simtotal length 18810
date '2020-08-01' simtotal length 18883
date '2020-09-01' simtotal length 19534
date '2020-10-01' simtotal length 20199
date '2020-11-01' simtotal length 21079
date '2020-12-01' simtotal length 21718
end date: '2020-12-01'
end date: '2021-01-01'
date '2021-01-01' simtotal length 21878
date '2021-02-01' simtotal length 22735
date '2021-03-01' simtotal length 23468
date '2021-04-01' simtotal length 23758
date '2021-05-01' simtotal length 23379
date '2021-06-01' simtotal length 23072
date '2021-07-01' simtotal length 22587
date '2021-08-01' simtotal length 22616
date '2021-09-01' simtotal length 23017
date '2021-10-01' simtotal length 23463
date '2021-11-01' simtotal length 23017
date '2021-12-01' simtotal length 23054
end date: '2021-12-01'
end date: '2022-01-01'
date '2022-01-01' simtotal length 22300
date '2022-02-01' simtotal length 22695
date '2022-03-01' simtotal length 21978
date '2022-04-01' simtotal length 20112
date '2022-05-01' simtotal length 18020
date '2022-06-01' simtotal length 15782
date '2022-07-01' simtotal length 14263
date '2022-08-01' simtotal length 13024
date '2022-09-01' simtotal length 11766
date '2022-10-01' simtotal length 10355
date '2022-11-01' simtotal length 8802
date '2022-12-01' simtotal length 6538
end date: '2022-12-01'
end date: '2023-01-01'
date '2023-01-01' simtotal length 4093
date '2023-02-01' simtotal length 1576
date '2023-03-01' simtotal length 0
date '2023-04-01' simtotal length 0
date '2023-05-01' simtotal length 0
date '2023-06-01' simtotal length 0
date '2023-07-01' simtotal length 0
date '2023-08-01' simtotal length 0
date '2023-09-01' simtotal length 0
date '2023-10-01' simtotal length 0
date '2023-11-01' simtotal length 0
date '2023-12-01' simtotal length 0
end date: '2023-12-01'

In [ ]:
## computer has memory limits, so split toolstart into branches
skip_section=1
if (skip_section==0):
    start_year = deepcopy(start_year_base)

    while start_year < today.year+1:
        start_year += 1
        print('start year: '+str(start_year))

        for i in range(1,13):
            if i < 10:
                start_date = r"'"+str(start_year-1)+r"-0"+str(i)+r"-01'"
                end_date = r"'"+str(start_year)+r"-0"+str(i)+r"-01'"
            else:
                start_date = r"'"+str(start_year-1)+r"-"+str(i)+r"-01'"
                end_date = r"'"+str(start_year)+r"-"+str(i)+r"-01'"

    #         sql_query_clustered = "select user from toolstart where user in " + str(tuple(clustered_NH_username2['username']))\
    #             +" and datetime <= "+end_date+" and datetime >= "+start_date
            sql_query_clustered = "select user from toolstart where user in " + str(tuple(clustered_NH_username['username']))\
                +" and datetime <= "+end_date+" and datetime >= "+start_date
            clustered_users = pd.read_sql_query(sql_query_clustered, nanohub_metrics_db)

            sql_query_m_clustered = "select user from toolstart where user in " + str(tuple(mike_clustered_NH_username['username']))\
                +" and datetime <= "+end_date+" and datetime >= "+start_date
            clustered_m_users = pd.read_sql_query(sql_query_m_clustered, nanohub_metrics_db)

            sql_query_x_clustered = "select user from toolstart where user in " + str(tuple(xufeng_clustered_NH_username['username']))\
                +" and datetime <= "+end_date+" and datetime >= "+start_date
            clustered_x_users = pd.read_sql_query(sql_query_x_clustered, nanohub_metrics_db)

            sql_query_mx_clustered = "select user from toolstart where user in " + str(tuple(mike_xufeng_clustered_NH_username['username']))\
                +" and datetime <= "+end_date+" and datetime >= "+start_date
            clustered_mx_users = pd.read_sql_query(sql_query_mx_clustered, nanohub_metrics_db)


    #         sql_query_self = "select user from toolstart where user in " + str(tuple(self_NH_username2['username']))\
    #             +" and user != 'instanton' and user != 'gridstat' and datetime <= "+end_date+" and datetime >= "+start_date
    #        sql_query_self = "select user from toolstart where user in " + str(tuple(self_study_usernames))\
    #            +" and user != 'instanton' and user != 'gridstat' and datetime <= "+end_date+" and datetime >= "+start_date
    #        self_users = pd.read_sql_query(sql_query_self, nanohub_metrics_db) #engine_metrics #.drop_duplicates()

            print('date'+str(start_date)+ 'clustered_users =',len(clustered_users.drop_duplicates()), \
                  'clustered_m_users =',len(clustered_m_users.drop_duplicates()), \
                  'clustered_x_users =',len(clustered_x_users.drop_duplicates()), \
                  'clustered_mx_users =',len(clustered_mx_users.drop_duplicates())     )


            clustered_track.append(clustered_users.drop_duplicates().shape[0])
            clustered_m_track.append(clustered_m_users.drop_duplicates().shape[0])
            clustered_x_track.append(clustered_x_users.drop_duplicates().shape[0])
            clustered_mx_track.append(clustered_mx_users.drop_duplicates().shape[0])
    #        self_track.append(self_users.drop_duplicates().shape[0])
    #         print('start_date: '+start_date)
    #         print('end_date: '+end_date)  
        print('start year: '+str(start_year))
        cache_clustered_track = pd.DataFrame()
        cache_clustered_track['track'] = clustered_track
        cache_clustered_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_clustered_track.csv')
        cache_clustered_track.to_csv(cwd+'/cached_data/clustered_track.csv')
        cache_clustered_track = []

        cache_clustered_m_track = pd.DataFrame()
        cache_clustered_m_track['track'] = clustered_m_track
        cache_clustered_m_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_clustered_m_track.csv')
        cache_clustered_m_track.to_csv(cwd+'/cached_data/clustered_m_track.csv')
        cache_clustered_m_track = []

        cache_clustered_x_track = pd.DataFrame()
        cache_clustered_x_track['track'] = clustered_x_track
        cache_clustered_x_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_clustered_x_track.csv')
        cache_clustered_x_track.to_csv(cwd+'/cached_data/clustered_x_track.csv')
        cache_clustered_x_track = []

        cache_clustered_mx_track = pd.DataFrame()
        cache_clustered_mx_track['track'] = clustered_mx_track
        cache_clustered_mx_track.to_csv(cwd+'/cached_data/'+ str(start_year)+'_clustered_mx_track.csv')
        cache_clustered_mx_track.to_csv(cwd+'/cached_data/clustered_mx_track.csv')
        cache_clustered_mx_track = []

    #    cache_self_track = pd.DataFrame()
    #    cache_self_track['track'] = self_track
    #    cache_self_track.to_csv(cwd+'/cached_data/self_track.csv')
    #    cache_self_track = []

In [ ]:
# all_months_list = list()
# for this_year in range(start_year_base+1,today.year+2):
#     if cache_flag == True:
#         for this_month in range(1,today.month+1):
#             all_months_list.append(datetime.datetime(this_year, this_month, 1))
#     else:
#         for this_month in range(1,12+1):
#             all_months_list.append(datetime.datetime(this_year, this_month, 1))

In [ ]:
print(len(clustered_track))
print(len(clustered_m_track))
print(len(clustered_x_track))
print(len(clustered_mx_track))
print(len(all_months_list))
print(len(researcher_track))

In [ ]:
#print(user_breakdown_df2.head())

In [ ]:

if cache_flag == True:
    user_breakdown_df2 = pd.DataFrame()
    user_breakdown_df2['year_month'] = all_months_list
    user_breakdown_df2['clustered_track'] = clustered_track
    user_breakdown_df2['clustered_m_track'] = clustered_m_track
    user_breakdown_df2['clustered_x_track'] = clustered_x_track
    user_breakdown_df2['clustered_mx_track'] = clustered_mx_track
    user_breakdown_df2['self_identified_track'] = self_identified_track
    user_breakdown_df2['self2_track'] = self2_track
    user_breakdown_df2['researcher_track'] = researcher_track
    
    user_breakdown_df = pd.concat([user_breakdown_df, user_breakdown_df2], ignore_index=True)
    display(user_breakdown_df.head(2))
else:
    user_breakdown_df = pd.DataFrame()
    if today.month == 12:
        user_breakdown_df['year_month'] = all_months_list #months_bin['year_month'].to_list()[13:]
        user_breakdown_df['clustered_track'] = clustered_track#[:len(all_months_list)]
        user_breakdown_df['clustered_m_track'] = clustered_m_track#[:len(all_months_list)]
        user_breakdown_df['clustered_x_track'] = clustered_x_track#[:len(all_months_list)]
        user_breakdown_df['clustered_mx_track'] = clustered_mx_track#[:len(all_months_list)]
        user_breakdown_df['self_identified_track'] = self_identified_track
        user_breakdown_df['self2_track'] = self2_track#[:len(all_months_list)]
        user_breakdown_df['researcher_track'] = researcher_track#[:len(all_months_list)]        
    else:
        user_breakdown_df['year_month'] = all_months_list #-(12-today.month)
        user_breakdown_df['clustered_track'] = clustered_track#[:len(all_months_list[:])]
        user_breakdown_df['clustered_m_track'] = clustered_m_track#[:len(all_months_list[:])]
        user_breakdown_df['clustered_x_track'] = clustered_x_track#[:len(all_months_list[:])]
        user_breakdown_df['clustered_mx_track'] = clustered_mx_track#[:len(all_months_list[:])]
        user_breakdown_df['self_identified_track'] = self_identified_track
        user_breakdown_df['self2_track'] = self2_track#[:len(all_months_list[:])]
        user_breakdown_df['researcher_track'] = researcher_track#[:len(all_months_list[:])]
    display(user_breakdown_df.head(2))

In [ ]:
# user_breakdown_df.to_csv(cwd+'/cached_data/temp.csv')

In [ ]:
import re

In [ ]:
## read the dev_flags.txt to determine where to save
with open(cwd+'/dev_flags.txt','r') as f:
    raw_flags = f.read()
flag_pattern = re.compile(r'= \w+')
flags1 = re.findall(flag_pattern,raw_flags)    
flags_result = [i[2:] for i in flags1]
dev_flag = flags_result[0]
prod_flag = flags_result[1]

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt
sns.set()
sns.set_style("whitegrid")

plt.figure(figsize=(9,6))
# user_breakdown_df2 = user_breakdown_df.iloc[:-(12-today.month),:]
user_breakdown_df2 = user_breakdown_df.iloc[:-12-(12-today.month),:]
plt.stackplot(user_breakdown_df2.year_month, \
#               user_breakdown_df2[['clustered_track','self_track']].to_numpy().T, \
#              labels=['Classroom', 'Unclassified'], \
#              colors=['green', 'orange']); #Self-study              
              user_breakdown_df2[['clustered_m_track', 'clustered_mx_track', 'clustered_x_track', 'researcher_track','self_identified_track','self_track']].to_numpy().T, \
             labels=['Classroom M','Classroom MX','Classroom X','Research', 'Researcher','Unclassified'], \
             colors=['lawngreen','green', 'yellowgreen','red', 'fuchsia','orange']); #Self-study

plt.legend(loc='upper left')#,fontsize=14);
plt.ylabel('12-month Trailing Total')#,fontsize=15)
plt.xlim([datetime.datetime(2001,1,1), datetime.datetime(2021,7,1)])#,fontsize=15)
# plt.show()

if dev_flag == 'True':
    plt.savefig(cwd+'/plots_local/300_simusers_class_res_unclass_12months_GK.eps', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_local/300_simusers_class_res_unclass_12months_GK.pdf', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_local/300_simusers_class_res_unclass_12months_GK.png', dpi=300, bbox_inches='tight')
elif prod_flag == 'True':
    plt.savefig(cwd+'/plots_production/300_simusers_class_res_unclass_12months_GK.eps', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_production/300_simusers_class_res_unclass_12months_GK.pdf', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_production/300_simusers_class_res_unclass_12months_GK.png', dpi=300, bbox_inches='tight')
else:
    print('no printing flag is active')

In [ ]:
total = user_breakdown_df2['clustered_track'].to_numpy()+user_breakdown_df2['researcher_track'].to_numpy()+\
                        user_breakdown_df2['self_track'].to_numpy() + user_breakdown_df2['self_identified_track'].to_numpy()
display(len(total))
user_breakdown_df2['clustered_track_per'] = 100*np.divide(user_breakdown_df2['clustered_track'],total)
user_breakdown_df2['self_identified_track_per'] = 100*np.divide(user_breakdown_df2['self_identified_track'], total)
user_breakdown_df2['researcher_track_per'] = 100*np.divide(user_breakdown_df2['researcher_track'], total)
user_breakdown_df2['self_track_per'] = 100*np.divide(user_breakdown_df2['self_track'], total)

In [ ]:
plt.figure(figsize=(9,6))
plt.plot(user_breakdown_df2.year_month, user_breakdown_df2.clustered_track_per, label='classroom', \
             color='green');
plt.plot(user_breakdown_df2.year_month, user_breakdown_df2.researcher_track_per, label='research', \
             color='red');
plt.plot(user_breakdown_df2.year_month, user_breakdown_df2.self_identified_track_per, label='self-identified', \
             color='magenta');
plt.plot(user_breakdown_df2.year_month, user_breakdown_df2.self_track_per, label='self-study', \
             color='orange');

plt.ylim([0, 100])
plt.legend(loc='upper right');
plt.ylabel('Percentage (%)');
plt.xlim([datetime.datetime(2001,1,1), datetime.datetime(2021,7,1)])
# plt.show()

if dev_flag == 'True':
    plt.savefig(cwd+'/plots_local/300_simusers_class_res_unclass_12months_percent_copied.eps', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_local/300_simusers_class_res_unclass_12months_percent_copied.pdf', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_local/300_simusers_class_res_unclass_12months_percent_copied.png', dpi=300, bbox_inches='tight')
elif prod_flag == 'True':
    plt.savefig(cwd+'/plots_production/300_simusers_class_res_unclass_12months_percent_copied.eps', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_production/300_simusers_class_res_unclass_12months_percent_copied.pdf', dpi=300, bbox_inches='tight')
    plt.savefig(cwd+'/plots_production/300_simusers_class_res_unclass_12months_percent_copied.png', dpi=300, bbox_inches='tight')
else:
    print('no printing flag is active')

In [ ]:
user_breakdown_df2.to_csv(cwd+'/cached_data/nh_user_breakdown.csv')